/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controller;
import Modelo.Clases.Producto;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author USUARIO
 */
public class GUI_Supermercado extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Supermercado
     */
    public GUI_Supermercado() {
        initComponents();
        
        this.tblConsultar.getTableHeader().setFont(new Font("Roboto Light", Font.BOLD, 12));
        this.tblConsultar.getTableHeader().setBackground(Color.red);
        this.tblConsultar.getTableHeader().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabNavegacion = new javax.swing.JTabbedPane();
        pnlRegistrar = new javax.swing.JPanel();
        lblNombre_Register = new javax.swing.JLabel();
        lblCantidad_Register = new javax.swing.JLabel();
        lblPrecio_Register = new javax.swing.JLabel();
        lblCategoria_Register = new javax.swing.JLabel();
        txtNombre_Register = new javax.swing.JTextField();
        txtPrecio_Register = new javax.swing.JTextField();
        txtCantidad_Register = new javax.swing.JTextField();
        cmbCategoria_Register = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        pnlConsultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultar = new javax.swing.JTable();
        txtId_Buscar = new javax.swing.JTextField();
        lblId_Consult = new javax.swing.JLabel();
        txtCantidad_Consult = new javax.swing.JTextField();
        lblCantidad_Consult = new javax.swing.JLabel();
        lblPrecioConsult = new javax.swing.JLabel();
        txtPrecio_Consult = new javax.swing.JTextField();
        cmbCategoria_Consult = new javax.swing.JComboBox<>();
        lblCategoria_Consult = new javax.swing.JLabel();
        txtNombre_Consult = new javax.swing.JTextField();
        lblNombre_Consult = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));

        tabNavegacion.setBackground(new java.awt.Color(255, 102, 51));
        tabNavegacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabNavegacion.setFocusCycleRoot(true);
        tabNavegacion.setFocusable(false);
        tabNavegacion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        tabNavegacion.setName(""); // NOI18N

        pnlRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre_Register.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblNombre_Register.setText("NOMBRE");

        lblCantidad_Register.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblCantidad_Register.setText("CANTIDAD");

        lblPrecio_Register.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblPrecio_Register.setText("PRECIO");

        lblCategoria_Register.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblCategoria_Register.setText("CATEGORIA");

        txtNombre_Register.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre_Register.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre_Register.setText("Nombre del producto");
        txtNombre_Register.setBorder(null);
        txtNombre_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombre_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombre_RegisterFocusLost(evt);
            }
        });

        txtPrecio_Register.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio_Register.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio_Register.setText("Precio del producto");
        txtPrecio_Register.setBorder(null);
        txtPrecio_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecio_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecio_RegisterFocusLost(evt);
            }
        });
        txtPrecio_Register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldsNumber_Register_KeyTyped(evt);
            }
        });

        txtCantidad_Register.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCantidad_Register.setForeground(new java.awt.Color(204, 204, 204));
        txtCantidad_Register.setText("Cantidad del producto");
        txtCantidad_Register.setBorder(null);
        txtCantidad_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidad_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad_RegisterFocusLost(evt);
            }
        });
        txtCantidad_Register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldsNumber_Register_KeyTyped(evt);
            }
        });

        cmbCategoria_Register.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbCategoria_Register.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "ASEO", "VIVERES" }));
        cmbCategoria_Register.setToolTipText("");
        cmbCategoria_Register.setBorder(null);
        cmbCategoria_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(0, 134, 190));
        btnGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPrecio_Register)
                                .addComponent(lblNombre_Register)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(txtNombre_Register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCantidad_Register)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(txtCantidad_Register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(lblCategoria_Register)
                                .addComponent(cmbCategoria_Register, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlRegistrarLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblNombre_Register)
                .addGap(18, 18, 18)
                .addComponent(txtNombre_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCantidad_Register)
                .addGap(18, 18, 18)
                .addComponent(txtCantidad_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrecio_Register)
                .addGap(18, 18, 18)
                .addComponent(txtPrecio_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria_Register)
                .addGap(18, 18, 18)
                .addComponent(cmbCategoria_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabNavegacion.addTab("Registrar", pnlRegistrar);

        pnlConsultar.setBackground(new java.awt.Color(255, 255, 255));
        pnlConsultar.setName("consultar"); // NOI18N
        pnlConsultar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlConsultarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tblConsultar.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tblConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Cetegoria", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsultar.setFocusable(false);
        tblConsultar.setShowVerticalLines(false);
        tblConsultar.getTableHeader().setResizingAllowed(false);
        tblConsultar.getTableHeader().setReorderingAllowed(false);
        tblConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsultar);

        txtId_Buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtId_BuscarFocusGained(evt);
            }
        });
        txtId_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldsNumber_Consult_KeyPressed(evt);
            }
        });

        lblId_Consult.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        lblId_Consult.setText("ID:");

        txtCantidad_Consult.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsConsult_CaretUpdate(evt);
            }
        });
        txtCantidad_Consult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldsNumber_Consult_KeyPressed(evt);
            }
        });

        lblCantidad_Consult.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        lblCantidad_Consult.setText("Cantidad:");

        lblPrecioConsult.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        lblPrecioConsult.setText("Precio:");

        txtPrecio_Consult.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsConsult_CaretUpdate(evt);
            }
        });
        txtPrecio_Consult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldsNumber_Consult_KeyPressed(evt);
            }
        });

        cmbCategoria_Consult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "ASEO", "VIVERES" }));
        cmbCategoria_Consult.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoria_ConsultItemStateChanged(evt);
            }
        });

        lblCategoria_Consult.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        lblCategoria_Consult.setText("Categoria:");

        txtNombre_Consult.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsConsult_CaretUpdate(evt);
            }
        });

        lblNombre_Consult.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        lblNombre_Consult.setText("Nombre: ");

        btnActualizar.setBackground(new java.awt.Color(0, 204, 0));
        btnActualizar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 134, 190));
        btnBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrecio_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(txtNombre_Consult))
                                    .addComponent(lblPrecioConsult)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria_Consult)
                                    .addComponent(cmbCategoria_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCantidad_Consult)
                                    .addComponent(btnActualizar)))
                            .addComponent(lblId_Consult))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre_Consult)
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addComponent(txtId_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblId_Consult)
                .addGap(1, 1, 1)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre_Consult)
                    .addComponent(lblCantidad_Consult))
                .addGap(1, 1, 1)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addComponent(lblPrecioConsult)
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecio_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCategoria_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 110, Short.MAX_VALUE))
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEliminar)
                                    .addComponent(btnActualizar))
                                .addGap(32, 32, 32))))
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addComponent(lblCategoria_Consult)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tabNavegacion.addTab("Consultar", pnlConsultar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabNavegacion, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabNavegacion, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void clearFields() {
        this.txtNombre_Register.setText("Nombre del producto");
        this.txtNombre_Register.setForeground(Color.gray);
        this.txtCantidad_Register.setText("Cantidad del producto");
        this.txtCantidad_Register.setForeground(Color.gray);
        this.txtPrecio_Register.setText("Precio del producto");
        this.txtPrecio_Register.setForeground(Color.gray);
        
        this.cmbCategoria_Register.setSelectedItem("Seleccionar...");
    }
    private void setFields(String id, String nombre, String cantidad, String categoria, String precio){
        this.txtId_Buscar.setText(id);
        this.txtNombre_Consult.setText(nombre);
        this.txtCantidad_Consult.setText(cantidad);
        this.cmbCategoria_Consult.setSelectedItem(categoria);
        this.txtPrecio_Consult.setText(precio);
        
    }   
    private void consultarLista() {
        DefaultTableModel model = (DefaultTableModel) this.tblConsultar.getModel();
        model.setRowCount(0);
        
        List<Producto> productos = Controller.listarProductos();
        
        for (int i = 0; i < productos.size(); i++) {
            Producto p = productos.get(i);
            model.insertRow(i, new Object[] {p.getId(),p.getNombre(), p.getCantidad(),p.getCategoria(),p.getPrecio()});
            
        }
    }
    static String id, nombre, cantidad, categoria, precio;
    private void tblConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultarMouseClicked
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        DefaultTableModel model = (DefaultTableModel) this.tblConsultar.getModel();
        
        id = model.getValueAt(row, 0).toString();
        nombre = model.getValueAt(row, 1).toString();
        cantidad = model.getValueAt(row, 2).toString();
        categoria = model.getValueAt(row, 3).toString();
        precio = model.getValueAt(row, 4).toString();
        
        this.setFields(id, nombre, cantidad, categoria, precio);
        this.btnEliminar.setEnabled(true);
        this.enabledFileds(true);
        
    }//GEN-LAST:event_tblConsultarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String id = this.txtId_Buscar.getText();
        
        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese valores válidos",
                    "Verificación de campos", JOptionPane.WARNING_MESSAGE);
        }else {
            Controller.borrarProducto(Integer.valueOf(id));
            this.setFields("","","","Seleccionar...","");
            this.consultarLista();
            this.txtId_Buscar.setEnabled(true);
            this.enabledFileds(false);
            this.EnabledButtons(false);
            
            JOptionPane.showMessageDialog(null, "El producto con id= "+id+" \nfué eliminado...");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void enabledFileds(boolean _enable) {
        this.txtNombre_Consult.setEnabled(_enable);
        this.txtCantidad_Consult.setEnabled(_enable);
        this.txtPrecio_Consult.setEnabled(_enable);
        this.cmbCategoria_Consult.setEnabled(_enable);
    }
    private void pnlConsultarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlConsultarAncestorAdded
        this.consultarLista();
        this.enabledFileds(false);
        
        JOptionPane.showMessageDialog(null, "Lista consultada :)","Mensaje Informativo",
                JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_pnlConsultarAncestorAdded

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int _id = Integer.valueOf(this.txtId_Buscar.getText());
        String _nombre = this.txtNombre_Consult.getText();
        int _cantidad =  Integer.valueOf((this.txtCantidad_Consult.getText().equals("") ? "0": this.txtCantidad_Consult.getText()));
        String _categoria = this.cmbCategoria_Consult.getSelectedItem().toString();
        double _precio = Double.valueOf((this.txtPrecio_Consult.getText().equals("") ? "0" : this.txtPrecio_Consult.getText()));

        if (_nombre.length() == 0 || _cantidad == 0 || _categoria.equals("Seleccionar...") || _precio == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese valores válidos",
                    "Verificación de campos", JOptionPane.WARNING_MESSAGE);
        } else {
            Controller.actualizarProducto(_id,_nombre, _cantidad, _categoria, _precio);
            this.setFields("","","","Seleccionar...","");
            this.consultarLista();
            this.enabledFileds(false);
            this.EnabledButtons(false);
            
            JOptionPane.showMessageDialog(null, "El producto con id= "+_id+" \nfué actualizado...");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed
    private void EnabledButtons(boolean _enabled) {
        this.btnActualizar.setEnabled(_enabled);
        this.btnEliminar.setEnabled(_enabled);
    }
    private void txtId_BuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtId_BuscarFocusGained
 
        this.setFields(this.txtId_Buscar.getText(),"","","Seleccionar...","");
        this.btnEliminar.setEnabled(false);
        this.enabledFileds(false);
        this.EnabledButtons(false);
    }//GEN-LAST:event_txtId_BuscarFocusGained
    private boolean isFieldsEnabled() {
        return this.txtNombre_Consult.isEnabled() && 
               this.txtCantidad_Consult.isEnabled() &&
               this.txtPrecio_Consult.isEnabled();
    }
    private void txtsConsult_CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsConsult_CaretUpdate
       if ( this.isFieldsEnabled() ) {
            boolean isUpdated = (
                IsFieldUpdate(nombre, this.txtNombre_Consult.getText()) ||
                IsFieldUpdate(cantidad, this.txtCantidad_Consult.getText()) ||
                IsFieldUpdate(precio, this.txtPrecio_Consult.getText())
        );
        
        this.btnActualizar.setEnabled(isUpdated);
       }
    }//GEN-LAST:event_txtsConsult_CaretUpdate
    private boolean IsFieldUpdate(String finalCampo, String txtCampo) {
        
        if(finalCampo.length() != txtCampo.length()) {
           return true;
        }else {
            return !finalCampo.equals(txtCampo);
        }
    }
    private void cmbCategoria_ConsultItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoria_ConsultItemStateChanged
        String itemSelected = this.cmbCategoria_Consult.getSelectedItem().toString();
        this.btnActualizar.setEnabled(!categoria.equals(itemSelected));
    }//GEN-LAST:event_cmbCategoria_ConsultItemStateChanged

    private void fieldsNumber_Register_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldsNumber_Register_KeyTyped
      this.validateNumbers(evt);
    }//GEN-LAST:event_fieldsNumber_Register_KeyTyped
    private void validateNumbers(java.awt.event.KeyEvent evt) {
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }
    private void fieldsNumber_Consult_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldsNumber_Consult_KeyPressed
        this.validateNumbers(evt);
    }//GEN-LAST:event_fieldsNumber_Consult_KeyPressed

    private void txtNombre_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre_RegisterFocusGained
        this.focusGained(this.txtNombre_Register, "Nombre del producto");
    }//GEN-LAST:event_txtNombre_RegisterFocusGained

    private void txtNombre_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre_RegisterFocusLost
        this.focusLost(this.txtNombre_Register,"Nombre del producto");
    }//GEN-LAST:event_txtNombre_RegisterFocusLost

    private void txtCantidad_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad_RegisterFocusGained
        this.focusGained(this.txtCantidad_Register, "Cantidad del producto");
    }//GEN-LAST:event_txtCantidad_RegisterFocusGained

    private void txtCantidad_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad_RegisterFocusLost
        this.focusLost(this.txtCantidad_Register,"Cantidad del producto");
    }//GEN-LAST:event_txtCantidad_RegisterFocusLost

    private void txtPrecio_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecio_RegisterFocusGained
        this.focusGained(this.txtPrecio_Register, "Precio del producto");
    }//GEN-LAST:event_txtPrecio_RegisterFocusGained

    private void txtPrecio_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecio_RegisterFocusLost
        this.focusLost(this.txtPrecio_Register, "Precio del producto");
    }//GEN-LAST:event_txtPrecio_RegisterFocusLost

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int _id;
        if (!this.txtId_Buscar.getText().equals("")) {
            _id = Integer.valueOf(this.txtId_Buscar.getText());
            Producto p = Controller.obtenerProducto(_id);

            if (p != null) {
                id = p.getId() + "";
                nombre = p.getNombre();
                cantidad = String.valueOf(p.getCantidad());
                categoria = p.getCategoria();
                precio = String.valueOf(p.getPrecio());

                this.setFields(id, nombre, cantidad, categoria, precio);

                this.btnEliminar.setEnabled(true);
                this.btnActualizar.setEnabled(false);
                this.enabledFileds(true);

                JOptionPane.showMessageDialog(null, "Busqueda exitosa...!", "Mensaje Informativo",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {

                JOptionPane.showMessageDialog(null, "No se encontró el prodcuto\ncon id = " + id, "Busqueda Fallida",
                        JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID", "Error",
                        JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String _nombre = this.txtNombre_Register.getText();
        int _cantidad =  Integer.valueOf((this.txtCantidad_Register.getText().equals("Cantidad del producto")
                ? "0": this.txtCantidad_Register.getText()));
        String _categoria = this.cmbCategoria_Register.getSelectedItem().toString();
        double _precio = Double.valueOf((this.txtPrecio_Register.getText().equals("Precio del producto") ? "0" : this.txtPrecio_Register.getText()));
        System.out.println(_nombre);
        System.out.println(_cantidad);
        System.out.println(_precio);
        System.out.println(_categoria);
       
        if (_nombre.equals("Nombre del producto") || _cantidad == 0 || _categoria.equals("Seleccionar...") || _precio == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese valores válidos",
                    "Verificación de campos", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                 Controller.registrarProducto(_nombre, _cantidad, _categoria, _precio);
                JOptionPane.showMessageDialog(null, "Operación realizada correctamente");
                this.clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(GUI_Supermercado.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error: "+ex.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void focusLost(JTextField field, String placeholder) {
        
        if(field.getText().equals("")) {
            System.out.println("Entro aqui: "+field.getText());
            field.setForeground(Color.gray);
            field.setText(placeholder);
       }
    }
    private void focusGained(JTextField field, String placeholder) {
       
        if (field.getText().equals(placeholder)) {
            field.setText("");
            field.setForeground(Color.black); 
        }
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCategoria_Consult;
    private javax.swing.JComboBox<String> cmbCategoria_Register;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCantidad_Consult;
    private javax.swing.JLabel lblCantidad_Register;
    private javax.swing.JLabel lblCategoria_Consult;
    private javax.swing.JLabel lblCategoria_Register;
    private javax.swing.JLabel lblId_Consult;
    private javax.swing.JLabel lblNombre_Consult;
    private javax.swing.JLabel lblNombre_Register;
    private javax.swing.JLabel lblPrecioConsult;
    private javax.swing.JLabel lblPrecio_Register;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JTabbedPane tabNavegacion;
    private javax.swing.JTable tblConsultar;
    private javax.swing.JTextField txtCantidad_Consult;
    private javax.swing.JTextField txtCantidad_Register;
    private javax.swing.JTextField txtId_Buscar;
    private javax.swing.JTextField txtNombre_Consult;
    private javax.swing.JTextField txtNombre_Register;
    private javax.swing.JTextField txtPrecio_Consult;
    private javax.swing.JTextField txtPrecio_Register;
    // End of variables declaration//GEN-END:variables
}
